/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module delay_timer_ls7212(wb, clk, reset, trigger, mode_a, mode_b, delay_out_n);
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire [7:0] TIMER;
  input clk;
  output delay_out_n;
  input mode_a;
  input mode_b;
  wire out_low;
  input reset;
  wire reset_det1;
  wire reset_det2;
  wire reset_timer;
  wire reset_timer1;
  wire reset_timer2;
  wire timer_clear;
  wire timer_start;
  input trigger;
  wire trigger_sync_1;
  wire trigger_sync_2;
  input [7:0] wb;
  sky130_fd_sc_hd__clkinv_1 _225_ (
    .A(_011_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _226_ (
    .A(_081_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _227_ (
    .A(_084_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor2b_1 _228_ (
    .A(_088_),
    .B_N(_087_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2b_1 _229_ (
    .A_N(_087_),
    .B(_088_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xnor2_1 _230_ (
    .A(_087_),
    .B(_088_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__xor2_1 _231_ (
    .A(_087_),
    .B(_088_),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _232_ (
    .A(_027_),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(_028_),
    .B(_036_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand3_1 _234_ (
    .A(_028_),
    .B(_027_),
    .C(_036_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__o21ai_0 _235_ (
    .A1(_085_),
    .A2(_032_),
    .B1(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nor2_1 _236_ (
    .A(_033_),
    .B(_040_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__and3_1 _237_ (
    .A(_013_),
    .B(_012_),
    .C(_011_),
    .X(_041_)
  );
  sky130_fd_sc_hd__and3_1 _238_ (
    .A(_015_),
    .B(_014_),
    .C(_041_),
    .X(_042_)
  );
  sky130_fd_sc_hd__a21oi_1 _239_ (
    .A1(_014_),
    .A2(_041_),
    .B1(_015_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor2_1 _240_ (
    .A(_042_),
    .B(_043_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _241_ (
    .A(_016_),
    .B(_042_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__xor2_1 _242_ (
    .A(_016_),
    .B(_042_),
    .X(_007_)
  );
  sky130_fd_sc_hd__nand3_1 _243_ (
    .A(_016_),
    .B(_017_),
    .C(_042_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xnor2_1 _244_ (
    .A(_017_),
    .B(_044_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _245_ (
    .A(_018_),
    .B(_045_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a21boi_0 _246_ (
    .A1(_095_),
    .A2(_036_),
    .B1_N(_017_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor3b_1 _247_ (
    .A(_018_),
    .B(_035_),
    .C_N(_096_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor3b_1 _248_ (
    .A(_017_),
    .B(_035_),
    .C_N(_095_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a21boi_0 _249_ (
    .A1(_096_),
    .A2(_036_),
    .B1_N(_018_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor4_1 _250_ (
    .A(_046_),
    .B(_047_),
    .C(_048_),
    .D(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2_1 _251_ (
    .A(_093_),
    .B(_036_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(_094_),
    .B(_036_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__o22ai_1 _253_ (
    .A1(_015_),
    .A2(_051_),
    .B1(_052_),
    .B2(_016_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(_016_),
    .B(_052_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__and2_0 _255_ (
    .A(_015_),
    .B(_051_),
    .X(_055_)
  );
  sky130_fd_sc_hd__nor4bb_1 _256_ (
    .A(_055_),
    .B(_053_),
    .C_N(_050_),
    .D_N(_054_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor3b_1 _257_ (
    .A(_014_),
    .B(_035_),
    .C_N(_092_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(_091_),
    .B(_036_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor3b_1 _259_ (
    .A(_013_),
    .B(_035_),
    .C_N(_091_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a21boi_0 _260_ (
    .A1(_091_),
    .A2(_036_),
    .B1_N(_013_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a21boi_0 _261_ (
    .A1(_092_),
    .A2(_036_),
    .B1_N(_014_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__or4_1 _262_ (
    .A(_057_),
    .B(_059_),
    .C(_060_),
    .D(_061_),
    .X(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _263_ (
    .A(_090_),
    .B(_036_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a21oi_1 _264_ (
    .A1(_089_),
    .A2(_036_),
    .B1(_002_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(_012_),
    .B(_063_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__maj3_1 _266_ (
    .A(_012_),
    .B(_063_),
    .C(_064_),
    .X(_066_)
  );
  sky130_fd_sc_hd__o32ai_1 _267_ (
    .A1(_013_),
    .A2(_058_),
    .A3(_061_),
    .B1(_062_),
    .B2(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__o21ai_0 _268_ (
    .A1(_057_),
    .A2(_067_),
    .B1(_056_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2b_1 _269_ (
    .A(_049_),
    .B_N(_048_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a311oi_1 _270_ (
    .A1(_050_),
    .A2(_053_),
    .A3(_054_),
    .B1(_069_),
    .C1(_047_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand3_1 _271_ (
    .A(_089_),
    .B(_002_),
    .C(_036_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor4b_1 _272_ (
    .A(_062_),
    .B(_064_),
    .C(_065_),
    .D_N(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a22o_1 _273_ (
    .A1(_068_),
    .A2(_070_),
    .B1(_072_),
    .B2(_056_),
    .X(_073_)
  );
  sky130_fd_sc_hd__a2111oi_0 _274_ (
    .A1(_034_),
    .A2(_073_),
    .B1(_080_),
    .C1(_086_),
    .D1(_033_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__a31oi_1 _275_ (
    .A1(_031_),
    .A2(_082_),
    .A3(_086_),
    .B1(_033_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _276_ (
    .A(_080_),
    .B(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor3_1 _277_ (
    .A(_027_),
    .B(_038_),
    .C(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a41oi_1 _278_ (
    .A1(_080_),
    .A2(_028_),
    .A3(_027_),
    .A4(_036_),
    .B1(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__o311ai_0 _279_ (
    .A1(_080_),
    .A2(_033_),
    .A3(_073_),
    .B1(_038_),
    .C1(_037_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o311ai_0 _280_ (
    .A1(_028_),
    .A2(_037_),
    .A3(_074_),
    .B1(_078_),
    .C1(_079_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a31oi_1 _281_ (
    .A1(_027_),
    .A2(_086_),
    .A3(_036_),
    .B1(_033_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__or3_1 _282_ (
    .A(_080_),
    .B(_028_),
    .C(_029_),
    .X(_010_)
  );
  sky130_fd_sc_hd__xor2_1 _283_ (
    .A(_012_),
    .B(_011_),
    .X(_003_)
  );
  sky130_fd_sc_hd__a21oi_1 _284_ (
    .A1(_012_),
    .A2(_011_),
    .B1(_013_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(_041_),
    .B(_030_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__xor2_1 _286_ (
    .A(_014_),
    .B(_041_),
    .X(_005_)
  );
  sky130_fd_sc_hd__nor2_1 _287_ (
    .A(_033_),
    .B(_040_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor2_1 _288_ (
    .A(_033_),
    .B(_040_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor2_1 _289_ (
    .A(_033_),
    .B(_040_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor2_1 _290_ (
    .A(_033_),
    .B(_040_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor2_1 _291_ (
    .A(_033_),
    .B(_040_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _292_ (
    .A(_033_),
    .B(_040_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2_1 _293_ (
    .A(_033_),
    .B(_040_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__dfxtp_1 _294_ (
    .CLK(clk),
    .D(_001_),
    .Q(delay_out_n)
  );
  sky130_fd_sc_hd__dfxtp_1 _295_ (
    .CLK(clk),
    .D(trigger),
    .Q(trigger_sync_1)
  );
  sky130_fd_sc_hd__dfxtp_1 _296_ (
    .CLK(clk),
    .D(trigger_sync_1),
    .Q(trigger_sync_2)
  );
  sky130_fd_sc_hd__dfxtp_1 _297_ (
    .CLK(clk),
    .D(reset_timer),
    .Q(reset_timer1)
  );
  sky130_fd_sc_hd__dfxtp_1 _298_ (
    .CLK(clk),
    .D(reset_timer1),
    .Q(reset_timer2)
  );
  sky130_fd_sc_hd__dfxtp_1 _299_ (
    .CLK(clk),
    .D(reset),
    .Q(reset_det1)
  );
  sky130_fd_sc_hd__dfxtp_1 _300_ (
    .CLK(clk),
    .D(reset_det1),
    .Q(reset_det2)
  );
  sky130_fd_sc_hd__dfrtp_1 _301_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(TIMER[0]),
    .RESET_B(_217_)
  );
  sky130_fd_sc_hd__dfrtp_1 _302_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(TIMER[1]),
    .RESET_B(_218_)
  );
  sky130_fd_sc_hd__dfrtp_1 _303_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(TIMER[2]),
    .RESET_B(_219_)
  );
  sky130_fd_sc_hd__dfrtp_1 _304_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(TIMER[3]),
    .RESET_B(_220_)
  );
  sky130_fd_sc_hd__dfrtp_1 _305_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(TIMER[4]),
    .RESET_B(_221_)
  );
  sky130_fd_sc_hd__dfrtp_1 _306_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(TIMER[5]),
    .RESET_B(_222_)
  );
  sky130_fd_sc_hd__dfrtp_1 _307_ (
    .CLK(clk),
    .D(_000_[6]),
    .Q(TIMER[6]),
    .RESET_B(_223_)
  );
  sky130_fd_sc_hd__dfrtp_1 _308_ (
    .CLK(clk),
    .D(_000_[7]),
    .Q(TIMER[7]),
    .RESET_B(_224_)
  );
  assign out_low = 1'h0;
  assign timer_start = 1'h0;
  assign _224_ = _026_;
  assign _015_ = TIMER[4];
  assign _000_[4] = _006_;
  assign _016_ = TIMER[5];
  assign _000_[5] = _007_;
  assign _017_ = TIMER[6];
  assign _000_[6] = _008_;
  assign _018_ = TIMER[7];
  assign _000_[7] = _009_;
  assign _087_ = trigger_sync_1;
  assign _088_ = trigger_sync_2;
  assign _096_ = wb[7];
  assign _095_ = wb[6];
  assign _094_ = wb[5];
  assign _093_ = wb[4];
  assign _092_ = wb[3];
  assign _014_ = TIMER[3];
  assign _091_ = wb[2];
  assign _013_ = TIMER[2];
  assign _090_ = wb[1];
  assign _012_ = TIMER[1];
  assign _089_ = wb[0];
  assign _011_ = TIMER[0];
  assign _080_ = reset;
  assign _028_ = mode_b;
  assign _027_ = mode_a;
  assign _000_[0] = _002_;
  assign _081_ = reset_det1;
  assign _082_ = reset_det2;
  assign _086_ = trigger;
  assign reset_timer = _083_;
  assign _001_ = _010_;
  assign _085_ = reset_timer2;
  assign _084_ = reset_timer1;
  assign _000_[1] = _003_;
  assign _000_[2] = _004_;
  assign _000_[3] = _005_;
  assign _217_ = _019_;
  assign _218_ = _020_;
  assign _219_ = _021_;
  assign _220_ = _022_;
  assign _221_ = _023_;
  assign _222_ = _024_;
  assign _223_ = _025_;
endmodule
